name: Security Scan

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  quality-security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run Black
      run: black --check src/ tests/

    - name: Run Flake8
      run: flake8 src/ tests/

    - name: Run isort
      run: isort --check-only src/ tests/

    - name: Run Bandit
      run: bandit -r src/

    - name: Run Safety
      run: safety check

    - name: Run MyPy
      run: mypy src/

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform/
